# Generated by Django 3.1.2 on 2020-10-20 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_in',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_in',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.DO_NOTHING, to='v1.ingredientincomposition'),
            preserve_default=False,
        ),
    ]
