# Generated by Django 3.1.2 on 2020-10-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20201020_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientincomposition',
            name='units_of_measurement',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='units_of_measurement',
            field=models.CharField(choices=[('шт', 'шт'), ('г', 'г'), ('ст.л', 'ст.л'), ('ч.л', 'ч.л')], default=123, max_length=20),
            preserve_default=False,
        ),
    ]
