# Generated by Django 3.1.2 on 2020-10-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_auto_20201020_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(default=10),
        ),
    ]
