# Generated by Django 3.1.2 on 2020-10-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_recipe_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.CharField(blank=True, choices=[('завтрак', 'завтрак'), ('обед', 'обед'), ('обед', 'обед')], max_length=10),
        ),
    ]
