# Generated by Django 3.1.2 on 2020-10-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_recipe_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
    ]
